import { useEffect } from 'react';
import type { GetServerSidePropsContext, NextPage } from 'next'
import mercadopago from 'mercadopago';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'



const Home: NextPage = ({ teste, payment }: any) => {

  return (
    <div className={styles.container}>
      <Head>
        <title>App Mercado Pago</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <a href={payment.response.sandbox_init_point}>PAGAR</a>
        <a>R$10,50</a>
      </main>
    </div>
  )
}

export default Home

export async function getServerSideProps(ctx: GetServerSidePropsContext) {

  mercadopago.configure({
    access_token: `TEST-8453388674292536-011515-d3265b956ab5f6116fef05a278d67cac-294413052`
  });

  const payments = await mercadopago.preferences.create({
    items: [
      {
        title: 'Test',
        quantity: 1,
        currency_id: 'BRL',
        unit_price: 10.5
      }
    ],
    back_urls: {
      success: `https://simple-mercadopago-payments.vercel.app/success`,
      failure: `https://simple-mercadopago-payments.vercel.app/error`,
    }
  });

  return {
    props: {
      payment: JSON.parse(JSON.stringify(payments)),
      teste: 'teste',
    },
  }
}
