import { useEffect } from 'react';
import type { GetServerSidePropsContext, NextPage } from 'next'
import mercadopago from 'mercadopago';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'



const Home: NextPage = ({ teste, payment }: any) => {
  console.log(teste);
  console.log(payment);


  return (
    <div className={styles.container}>
      <Head>
        <title>App Mercado Pago</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <a href={payment.response.sandbox_init_point}>PAGAR</a>
      </main>
    </div>
  )
}

export default Home

export async function getServerSideProps(ctx: GetServerSidePropsContext) {

  mercadopago.configure({
    access_token: `${process.env.MERCADO_PAGO_SEGRET}`
  });

  const payments = await mercadopago.preferences.create({
    items: [
      {
        title: 'Test',
        quantity: 1,
        currency_id: 'BRL',
        unit_price: 10.5
      }
    ],
    back_urls: {
      success: `${process.env.MERCADO_PAGO_CALLBACK_SUCCESS}`,
      failure: `${process.env.MERCADO_PAGO_CALLBACK_ERROR}`,
    }
  });

  return {
    props: {
      payment: JSON.parse(JSON.stringify(payments)),
      teste: 'teste',
    },
  }
}
